from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from pathlib import Path

from controller import Robot

RADIO_RUEDA = 0.0205
DISTANCIA_EJES = 0.052
VEL_MAXIMA = 6.28

K_RHO = 0.8
V_MAX = 0.06
SEGMENT_TOL = 0.005
TURN_TOL = math.radians(1)
W_TURN = 1.2
TURN_EXTRA = math.radians(9.4245)
SEGMENT_EXTRA = 0.0

REPO_ROOT = Path(__file__).resolve().parents[2]
CONTROLLER_DIR = Path(__file__).resolve().parent
DEFAULT_PATH = REPO_ROOT / "scripts" / "output" / "laberinto1_path.json"
DEFAULT_CSV = REPO_ROOT / "data_sensores" / "trayectoria_ejecutada.csv"
TELEMETRY_INTERVAL_S = 1.0


def resolve_repo_path(path: Path) -> Path:
    if path.is_absolute():
        return path.resolve()
    if path.parts and path.parts[0] == "..":
        return (CONTROLLER_DIR / path).resolve()
    return (REPO_ROOT / path).resolve()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Follow A* path with turn-then-drive motion.")
    parser.add_argument(
        "--path",
        type=Path,
        default=DEFAULT_PATH,
        help="Path JSON generated by plan_path.py (e.g. scripts/output/{name}_path.json)",
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=DEFAULT_CSV,
        help="Output CSV for executed trajectory",
    )
    args = parser.parse_args()
    args.path = resolve_repo_path(args.path)
    args.csv = resolve_repo_path(args.csv)
    return args


def normalize_angle(angle: float) -> float:
    return (angle + math.pi) % (2.0 * math.pi) - math.pi


def segment_axis(p0: tuple[float, float], p1: tuple[float, float]) -> str:
    dx = p1[0] - p0[0]
    dy = p1[1] - p0[1]
    return "x" if abs(dx) >= abs(dy) else "y"


def segment_heading(p0: tuple[float, float], p1: tuple[float, float]) -> float:
    dx = p1[0] - p0[0]
    dy = p1[1] - p0[1]
    if abs(dx) >= abs(dy):
        return 0.0 if dx > 0 else math.pi
    return math.pi / 2 if dy > 0 else -math.pi / 2


def axis_distance(
    pose: tuple[float, float],
    target: tuple[float, float],
    axis: str,
) -> float:
    if axis == "x":
        return target[0] - pose[0]
    return target[1] - pose[1]


def load_waypoints(path: Path) -> tuple[list[tuple[float, float]], dict]:
    if not path.exists():
        raise FileNotFoundError(
            f"Path JSON not found: {path}\n"
            "Run from scripts/:\n"
            "  uv run python export_occupancy_grid.py --name NAME --start-cell CX,CY --goal-cell CX,CY\n"
            "  uv run python plan_path.py --name NAME"
        )

    data = json.loads(path.read_text(encoding="utf-8"))
    raw_waypoints = data.get("path_world")
    if not raw_waypoints or len(raw_waypoints) < 2:
        raise ValueError(f"Invalid path_world in {path}: expected at least 2 waypoints")

    waypoints = [(float(x), float(y)) for x, y in raw_waypoints]
    goal_cell = tuple(data.get("goal_cell", []))
    last_cell = tuple(data.get("path_cells", [[]])[-1])
    if goal_cell and last_cell and goal_cell != last_cell:
        print(
            f"[Advertencia] goal_cell {goal_cell} no coincide con ultimo path_cell {last_cell}",
            file=sys.stderr,
        )

    return waypoints, data


def clamp(value: float, low: float, high: float) -> float:
    return max(low, min(value, high))


def initial_heading_from_path(waypoints: list[tuple[float, float]]) -> float:
    if len(waypoints) < 2:
        return 0.0
    return segment_heading(waypoints[0], waypoints[1])


class TrajectoryLogger:
    def __init__(self, csv_path: Path) -> None:
        csv_path.parent.mkdir(parents=True, exist_ok=True)
        self._file = csv_path.open("w", encoding="utf-8", newline="")
        self._writer = csv.writer(self._file)
        self._writer.writerow(
            [
                "tiempo_s",
                "x_m",
                "y_m",
                "phi_rad",
                "waypoint_idx",
                "estado",
                "dist_wp_m",
                "dist_recorrida_m",
            ]
        )
        self._file.flush()

    def write_row(
        self,
        sim_time: float,
        x: float,
        y: float,
        phi: float,
        waypoint_idx: int,
        estado: str,
        dist_wp: float,
        dist_recorrida: float,
    ) -> None:
        self._writer.writerow(
            [
                round(sim_time, 3),
                round(x, 5),
                round(y, 5),
                round(phi, 5),
                waypoint_idx,
                estado,
                round(dist_wp, 5),
                round(dist_recorrida, 5),
            ]
        )
        self._file.flush()

    def close(self) -> None:
        self._file.close()


class DifferentialDrive:
    def __init__(self, robot: Robot, timestep: int, start_xy: tuple[float, float], start_phi: float) -> None:
        self.robot = robot
        self.timestep_s = timestep / 1000.0

        self.motor_left = robot.getDevice("left wheel motor")
        self.motor_right = robot.getDevice("right wheel motor")
        self.motor_left.setPosition(float("inf"))
        self.motor_right.setPosition(float("inf"))
        self.stop()

        self.encoder_left = robot.getDevice("left wheel sensor")
        self.encoder_right = robot.getDevice("right wheel sensor")
        self.encoder_left.enable(timestep)
        self.encoder_right.enable(timestep)

        self.encoder_left_prev = 0.0
        self.encoder_right_prev = 0.0
        self.first_step = True

        self.x = start_xy[0]
        self.y = start_xy[1]
        self.phi = start_phi

    def stop(self) -> None:
        self.motor_left.setVelocity(0.0)
        self.motor_right.setVelocity(0.0)

    def apply_wheel_speeds(self, omega_left: float, omega_right: float) -> None:
        omega_left = clamp(omega_left, -VEL_MAXIMA, VEL_MAXIMA)
        omega_right = clamp(omega_right, -VEL_MAXIMA, VEL_MAXIMA)
        self.motor_left.setVelocity(omega_left)
        self.motor_right.setVelocity(omega_right)

    def update_odometry(self) -> tuple[float, float]:
        left_pos = self.encoder_left.getValue()
        right_pos = self.encoder_right.getValue()

        if math.isnan(left_pos):
            left_pos = 0.0
        if math.isnan(right_pos):
            right_pos = 0.0

        if self.first_step:
            self.encoder_left_prev = left_pos
            self.encoder_right_prev = right_pos
            self.first_step = False
            return 0.0, 0.0

        delta_left = left_pos - self.encoder_left_prev
        delta_right = right_pos - self.encoder_right_prev
        self.encoder_left_prev = left_pos
        self.encoder_right_prev = right_pos

        delta_s_left = RADIO_RUEDA * delta_left
        delta_s_right = RADIO_RUEDA * delta_right
        delta_s = (delta_s_left + delta_s_right) / 2.0
        delta_phi = (delta_s_right - delta_s_left) / DISTANCIA_EJES

        phi_prev = self.phi
        self.phi = normalize_angle(self.phi + delta_phi)
        self.x += delta_s * math.cos(phi_prev + delta_phi / 2.0)
        self.y += delta_s * math.sin(phi_prev + delta_phi / 2.0)
        return delta_s, delta_phi

    def snap_to_waypoint(self, target: tuple[float, float], axis: str) -> None:
        if axis == "x":
            self.x = target[0]
        else:
            self.y = target[1]

    def rotate_in_place(self, required_turn_rad: float) -> None:
        if abs(required_turn_rad) < TURN_TOL:
            self.stop()
            return

        omega = math.copysign(W_TURN, required_turn_rad)
        omega_left = (-omega * DISTANCIA_EJES / 2.0) / RADIO_RUEDA
        omega_right = (omega * DISTANCIA_EJES / 2.0) / RADIO_RUEDA
        self.apply_wheel_speeds(omega_left, omega_right)

    def drive_straight(self, remaining_m: float) -> None:
        if remaining_m < 1e-6:
            self.stop()
            return

        v = clamp(K_RHO * remaining_m, 0.0, V_MAX)
        omega_left = v / RADIO_RUEDA
        omega_right = v / RADIO_RUEDA
        self.apply_wheel_speeds(omega_left, omega_right)


class PathFollower:
    def __init__(self, waypoints: list[tuple[float, float]], planned_length_m: float) -> None:
        self.waypoints = waypoints
        self.planned_length_m = planned_length_m
        self.index = 1
        self.state = "GIRAR"
        self.segment_axis = "x"
        self.target_heading = 0.0
        self.distance_traveled_m = 0.0
        self.segment_driven_m = 0.0
        self.segment_length_m = 0.0
        self.turn_accumulated_rad = 0.0
        self.required_turn_rad = 0.0
        self.prepare_segment(waypoints[0], waypoints[1])

    @property
    def current_waypoint(self) -> tuple[float, float]:
        return self.waypoints[self.index]

    @property
    def is_last_target(self) -> bool:
        return self.index >= len(self.waypoints) - 1

    def prepare_segment(self, p0: tuple[float, float], p1: tuple[float, float]) -> None:
        self.segment_axis = segment_axis(p0, p1)
        self.target_heading = segment_heading(p0, p1)

    def begin_advance_segment(
        self,
        start: tuple[float, float],
        target: tuple[float, float],
        axis: str,
    ) -> None:
        self.segment_driven_m = 0.0
        self.segment_length_m = abs(axis_distance(start, target, axis))

    def begin_turn(self, target_heading: float, current_phi: float) -> None:
        self.turn_accumulated_rad = 0.0
        self.required_turn_rad = normalize_angle(target_heading - current_phi)

    def update_segment(self, delta_s: float, phi: float, axis: str) -> None:
        if axis == "x":
            self.segment_driven_m += abs(delta_s * math.cos(phi))
        else:
            self.segment_driven_m += abs(delta_s * math.sin(phi))

    def update_turn(self, delta_phi: float) -> None:
        self.turn_accumulated_rad += delta_phi

    def advance_complete(self) -> bool:
        return self.segment_driven_m >= self.segment_length_m - SEGMENT_TOL + SEGMENT_EXTRA

    def turn_complete(self) -> bool:
        if abs(self.required_turn_rad) < TURN_TOL:
            return True
        return abs(self.turn_accumulated_rad) >= abs(self.required_turn_rad) - TURN_TOL + TURN_EXTRA

    def segment_remaining_m(self) -> float:
        return max(0.0, self.segment_length_m - self.segment_driven_m)

    def turn_remaining_rad(self) -> float:
        return max(0.0, abs(self.required_turn_rad) - abs(self.turn_accumulated_rad))

    def on_waypoint_reached(self) -> None:
        if self.is_last_target:
            self.state = "FIN"
            return

        from_wp = self.waypoints[self.index]
        self.index += 1
        self.prepare_segment(from_wp, self.waypoints[self.index])
        self.state = "GIRAR"

    def update_distance(self, delta_s: float) -> None:
        self.distance_traveled_m += abs(delta_s)


def main() -> int:
    args = parse_args()
    waypoints, path_data = load_waypoints(args.path)

    start_xy = (waypoints[0][0], waypoints[0][1])
    goal_xy = (waypoints[-1][0], waypoints[-1][1])

    robot = Robot()
    timestep = int(robot.getBasicTimeStep())
    start_phi = initial_heading_from_path(waypoints)
    drive = DifferentialDrive(robot, timestep, start_xy, start_phi)
    follower = PathFollower(waypoints, float(path_data.get("length_m", 0.0)))
    follower.begin_turn(follower.target_heading, start_phi)
    logger = TrajectoryLogger(args.csv)

    print(f"[Sistema] Ruta cargada: {args.path.resolve()}")
    print(f"[Sistema] CSV trayectoria: {args.csv.resolve()}")
    print(f"[Sistema] Waypoints: {len(waypoints)} | Longitud planificada: {follower.planned_length_m} m")
    print(f"[Sistema] Inicio: {start_xy} | Meta: {goal_xy}")
    print(f"[Sistema] Pose inicial odom: ({drive.x:.3f}, {drive.y:.3f}, {drive.phi:.3f})")
    print("[Sistema] Modo: avanzar recto + girar en esquinas (GIRAR/AVANZAR, odometria acumulada)")
    print("[Sistema] Coloca el E-puck sobre START_MARKER antes de simular.")

    last_telemetry_s = 0.0
    finished_logged = False
    progress = 0.0

    try:
        while robot.step(timestep) != -1:
            sim_time = robot.getTime()
            delta_s, delta_phi = drive.update_odometry()
            follower.update_distance(delta_s)

            if follower.state == "FIN":
                drive.stop()
                logger.write_row(
                    sim_time,
                    drive.x,
                    drive.y,
                    drive.phi,
                    follower.index,
                    follower.state,
                    progress,
                    follower.distance_traveled_m,
                )
                if not finished_logged:
                    print(
                        f"[t={sim_time:.1f}s] META alcanzada. "
                        f"Waypoints: {follower.index + 1}/{len(waypoints)}. "
                        f"Distancia planificada: {follower.planned_length_m} m | "
                        f"Distancia odometrica: {follower.distance_traveled_m:.2f} m"
                    )
                    finished_logged = True
                continue

            if follower.state == "GIRAR":
                follower.update_turn(delta_phi)
                progress = follower.turn_remaining_rad()
                drive.rotate_in_place(follower.required_turn_rad)
                if follower.turn_complete():
                    drive.phi = follower.target_heading
                    drive.stop()
                    follower.state = "AVANZAR"
                    follower.begin_advance_segment(
                        (drive.x, drive.y),
                        follower.current_waypoint,
                        follower.segment_axis,
                    )
                    print(
                        f"[t={sim_time:.1f}s] GIRAR completo "
                        f"(heading={math.degrees(follower.target_heading):.0f}deg, "
                        f"acum={math.degrees(follower.turn_accumulated_rad):.1f}deg) "
                        f"-> AVANZAR {follower.segment_length_m:.3f}m hacia wp "
                        f"{follower.index} {follower.current_waypoint}"
                    )
            else:
                follower.update_segment(delta_s, drive.phi, follower.segment_axis)
                progress = follower.segment_remaining_m()
                drive.drive_straight(progress)
                if follower.advance_complete():
                    drive.snap_to_waypoint(follower.current_waypoint, follower.segment_axis)
                    drive.stop()
                    reached = follower.current_waypoint
                    follower.on_waypoint_reached()
                    if follower.state == "FIN":
                        print(
                            f"[t={sim_time:.1f}s] META alcanzada en {reached}. "
                            f"Waypoints: {len(waypoints)}/{len(waypoints)}. "
                            f"Distancia planificada: {follower.planned_length_m} m | "
                            f"Distancia recorrida: {follower.distance_traveled_m:.2f} m"
                        )
                        finished_logged = True
                    else:
                        follower.begin_turn(follower.target_heading, drive.phi)
                        print(
                            f"[t={sim_time:.1f}s] Waypoint {follower.index - 1} alcanzado en {reached} "
                            f"(seg={follower.segment_driven_m:.3f}m) "
                            f"-> GIRAR hacia wp {follower.index} "
                            f"(heading={math.degrees(follower.target_heading):.0f}deg)"
                        )

            logger.write_row(
                sim_time,
                drive.x,
                drive.y,
                drive.phi,
                follower.index,
                follower.state,
                progress,
                follower.distance_traveled_m,
            )

            if sim_time - last_telemetry_s >= TELEMETRY_INTERVAL_S:
                if follower.state == "GIRAR":
                    detail = (
                        f"turn={math.degrees(follower.turn_accumulated_rad):.1f}/"
                        f"{math.degrees(follower.required_turn_rad):.1f}deg"
                    )
                else:
                    detail = (
                        f"seg={follower.segment_driven_m:.3f}/"
                        f"{follower.segment_length_m:.3f}m axis={follower.segment_axis}"
                    )
                print(
                    f"[t={sim_time:.1f}s] wp={follower.index}/{len(waypoints) - 1} "
                    f"pose=({drive.x:.2f},{drive.y:.2f},{math.degrees(drive.phi):.0f}deg) "
                    f"{detail} estado={follower.state}"
                )
                last_telemetry_s = sim_time
    finally:
        logger.close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
